### ISSUE TITLE
Update release documentation

### ISSUE THREAD

**Issue by abadger** [fedora-infra/fas#23] opened 2013-05-08 22:35 UTC
FAS has documented the steps to make a new release in the HACKING file.  This needs to be updated to use github and git flow instead of generic git against fedorahosted.org.  You can look at the packagedb or python-fedora release steps for ideas:
- https://github.com/fedora-infra/packagedb/blob/develop/README#L375
- https://github.com/fedora-infra/python-fedora/blob/develop/README#L226

Note that fas has a po compilation step built into its setup.py so it may not need to do some of the steps that those projects have.

**Comment by TridevGuha** [comment] 2015-09-25 09:42
Iwould like to work for this project. 
I have some questions:
0) Merge all features, hotfixes, etc that you want for this release into the
   develop branch in https://github.com/fedora-infra/packagedb/blob/develop/README#L375
 and this link https://github.com/fedora-infra/python-fedora/blob/develop/README#L226 gives 404 error.

**Comment by linux-modder** [comment] 2015-09-26 02:52
Tridev,

per the link at  L226 (the second link) it should be  updated to:
https://github.com/fedora-infra/python-fedora/blob/develop/README.rst

Not sure what you are having issues with at in the vicinity of  L375 can
you please elaborate what the issue is you are  encountering (or  the
confusion --whichever is the case)?

Corey W Sheldon
Freelance IT Consultant, Multi-Discipline Tutor
Ameridea LLC, Co-Founder, CTO
Fedora Ambassador, North America
(p) +1 (310) 909-7672

    "Have no way as way, no limitation as limitation. One must never
underestimate the power of boredom...from which creativity and laziness are
borne, which can spark great works of chaos and genius."

Find Me  on any of the sites  I teach /frequent:
https://gist.github.com/linux-modder/ac5dc6fa211315c633c9
---------------------------------------------------------------------------------------------------
PGP: 0xe958c5d6718bf597 FP = 2930 99EB 083D D332 0752 88C4 E958 C5D6 718B
F597
Tox: Corey84 || Linux-modder
9357BC6A5944A08AFC7D1EFFD61F6A73B9EABF8B2FB84ACF1DAC9A1A4D0A4705FFCCD0E5499B
Linphone: sip:linuxmodder

---------------------------------------------------------------------------------------------------

**Comment by TridevGuha** [comment] 2015-09-26 15:33
I am trying the project freshly from start again, if I feel issue, will certainly ask here :)

**Comment by TridevGuha** [comment] 2015-09-26 15:43
ok I will start the project freshly and if feel confusions will certainly ask :)

**Comment by TridevGuha** [comment] 2015-09-26 15:56
I am new to fedora easyfix, can you guide me what is the first step of this issue?

**Comment by laxathom** [comment] 2015-10-05 22:01
You would need to read this first: https://fedoraproject.org/wiki/Infrastructure/AppBestPractices#Making_a_release

also, we do archive the new release using:
```
git archive --format=tar.xz %current_release_branch . > fas-%release_version.tar.xz
```

**Comment by pypingou** [comment] 2015-10-06 07:31
@laxathom not via the setup.py?

**Comment by laxathom** [comment] 2015-10-12 14:51
Oh, both work. 
I tend to use git to make sure only committed data get into the tarball avoiding garbled local changes or the like.

**Comment by TridevGuha** [comment] 2015-11-06 16:04
is this issue closed? if not I would try to fix

**Comment by ryanlerch** [comment] 2021-04-12 09:54
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)

**Closed by ryanlerch** 2021-04-12 09:54 UTC
Labels: EasyFix
