### ISSUE TITLE
Fatal when expecting a 404

### ISSUE THREAD

**Issue by relrod** [fedora-infra/fas#17] opened 2013-04-24 23:10 UTC
We currently fatal/throw/500 when you go to: https://admin.fedoraproject.org/accounts/user/view/codeblock/foo

We should 404 instead.

**Comment by ardian** [comment] 2015-06-30 18:51
Is this issue still related, since fas is being rewritten should we invest time in this ?

**Comment by relrod** [comment] 2015-06-30 19:22
I haven't looked, but I suspect this is a 1-2 line patch to fix.

**Comment by relrod** [comment] 2015-06-30 19:54
I think it's still worth fixing - I don't know when the FAS rewrite is going to go live.

fwiw, the trace is this:

```
[Tue Jun 30 19:22:44 2015] [error] turbogears.access INFO 192.168.1.52 - - [30/Jun/2015:19:22:44 +0000] "GET /accounts/ HTTP/1.1" 200 7430 "" ""
[Tue Jun 30 19:22:44 2015] [error] cherrypy.msg INFO HTTP: Page handler: <bound method User.view of <fas.user.User object at 0x7fcc0dc84050>>
[Tue Jun 30 19:22:44 2015] [error] Traceback (most recent call last):
[Tue Jun 30 19:22:44 2015] [error]   File "/usr/lib/python2.6/site-packages/CherryPy-2.3.0-py2.6.egg/cherrypy/_cphttptools.py", line 121, in _run
[Tue Jun 30 19:22:44 2015] [error]     self.main()
[Tue Jun 30 19:22:44 2015] [error]   File "/usr/lib/python2.6/site-packages/CherryPy-2.3.0-py2.6.egg/cherrypy/_cphttptools.py", line 264, in main
[Tue Jun 30 19:22:44 2015] [error]     body = page_handler(*virtual_path, **self.params)
[Tue Jun 30 19:22:44 2015] [error]   File "<string>", line 3, in view
[Tue Jun 30 19:22:44 2015] [error]   File "/usr/lib/python2.6/site-packages/turbogears/identity/conditions.py", line 249, in require
[Tue Jun 30 19:22:44 2015] [error]     return fn(self, *args, **kwargs)
[Tue Jun 30 19:22:44 2015] [error] TypeError: view() got multiple values for keyword argument 'username'
```

**Comment by ardian** [comment] 2015-06-30 19:59
I would like to fix this, this is my first task as an apprentice, how do I proceed ?

kindly

**Comment by pypingou** [comment] 2015-06-30 20:29
You will need to get a local FAS instance running and see if you can reproduce this issue (which will help to fix it)

**Comment by pklos** [comment] 2015-07-27 09:06
Hi, Is anybody working on that issue? I will if not.

**Comment by pklos** [comment] 2015-07-28 12:16
I made some investigation... As I see there is view(self, username=None) method in user class which takes keyword parameter 'username'. In the path /accounts/user/view/$s everything after 'view' (which is called method name) (so $s in that example) is parameters so if sb calls /accounts/user/view/someuser will see user parameters listed. But if other sb call /accounts/user/view/someuser/foo or a few more 'sth/' are passing additional params to the view method. I think it's quite normal that server behaves like he has and throws 500.

**Comment by d1ndra** [comment] 2015-11-24 17:08
@pypingou Hey I would like to work on this if still needed. I was trying to start-fas on my system  which has TurboGears2 installed but I think it needs TurboGear which I was unable to install on my system due to 
<code>
Could not find a version that satisfies the requirement PEAK-Rules>=0.5a1.dev-r2555 (from TurboGears) (from versions: )
  Some externally hosted files were ignored as access to them may be unreliable (use --allow-external PEAK-Rules to allow).
No matching distribution found for PEAK-Rules>=0.5a1.dev-r2555 (from TurboGears)
</code>

Any idea what to do?

**Comment by pypingou** [comment] 2015-11-24 21:55
@d1ndra FAS2 runs on TurboGears 1 not 2, which mean you will need to use a virtual environment to get it to work on a recent system.

**Comment by d1ndra** [comment] 2015-11-24 23:08
@pypingou I tried doing that. I set up a virtualenv and installed Turbo Gears 1.5 on it, but when I ran start-fas I got the same error again.

<code>
File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3084, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 651, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'TurboGears' distribution was not found and is required by the application
</code>

Any help would be appreciated.

**Comment by pypingou** [comment] 2015-11-25 08:36
Which version of turbogears do you have in your venv? Might be worth trying with an old one like 1.1.3 (seems to be the one running in our machine).

**Comment by d1ndra** [comment] 2015-11-25 13:16
@pypingou Yeah, shifting to 1.1.3 worked. However there seem to be other modules missing, working on that.

**Comment by d1ndra** [comment] 2015-11-25 15:08
@pypingou All dependencies seem to have been resolved.

Although I am getting this error related to SQLAlchemy about which I don't have much idea. Should I reconfigure a tmp database on my own?
```
No sqlalchemy database configuration found!")
turbogears.database.DatabaseConfigurationError: No sqlalchemy database configuration found!
```

**Comment by pypingou** [comment] 2015-11-25 15:41
Did you see https://github.com/fedora-infra/fas/blob/develop/INSTALL#L31 ?

**Comment by d1ndra** [comment] 2015-11-25 16:16
@pypingou Yeah, I just saw it. Thanks. Can't believe I didn't notice it before and installed all those python packages manually -_-

**Comment by pypingou** [comment] 2015-11-25 21:26
Well, this might still be needed as the version in Fedora might be too recent :-/

**Comment by d1ndra** [comment] 2015-11-26 11:00
@pypingou Could you tell me where is username being stored as a dict and passed to view() in user.py

I can't figure out the source :confused:

**Comment by ryanlerch** [comment] 2021-04-12 09:54
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)

**Closed by ryanlerch** 2021-04-12 09:54 UTC
Labels: Bug, EasyFix
